name: Illumos Integration Tests

on:
  push:
    branches: [ "main", "illumos-ci" ]
  pull_request:

jobs:
  test-illumos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Tests inside OmniOS VM
        uses: vmactions/omnios-vm@v1
        with:
          prepare: |
            pkg refresh
            pkg install developer/build/onbld rust
          # The Rust package has no rustup llvm-tools component, so the tests of
          # coverage-based test selection are skipped, although CI is set in the VM.
          run: |
            CARGO_MUTANTS_TESTS_ALLOW_MISSING_LLVM_TOOLS=1 cargo test
